plugins {
  // https://github.com/nemerosa/versioning
  id 'net.nemerosa.versioning' version '3.1.0'
}

ext {
  testingCommonGradle = "https://raw.githubusercontent.com/interlok-testing/testing_common/refs/heads/master/common.gradle?timestamp=${new Date().getTime()}"
  //testingCommonGradle = "../interlok-testing-common/common.gradle"
}

allprojects {
  apply from: "${testingCommonGradle}"
  // specify the version of the configuration.
  version=versioning.info.full
}


dependencies {
  interlokRuntime ("com.adaptris:interlok-json:$interlokVersion") { changing=true }
  interlokRuntime ("com.adaptris:interlok-csv:$interlokVersion") { changing=true }
  interlokRuntime ("com.adaptris:interlok-csv-json:$interlokVersion") { changing=true }
  interlokRuntime ("com.adaptris:interlok-service-tester:$interlokServiceTesterVersion") { changing=true }
  interlokRuntime ("com.adaptris:interlok-service-tester-xml:$interlokServiceTesterVersion") { changing=true }

  interlokRuntime ("org.apache.derby:derby:10.15.2.0") { changing=true }
  interlokRuntime ("org.apache.derby:derbyshared:10.15.2.0") { changing=true }
  interlokRuntime ("org.apache.derby:derbytools:10.15.2.0") { changing=true }
}


tasks.named('functionalTest') {
  interlokServiceTest.enabled = false
  interlokServiceTestReport.enabled = false
}